### PR TITLE
Switch to esm

### PR DESCRIPTION
**Pull request by jimmywarting**
Hope u don't mind if i executed `standard --fix` style looked similar, it changed all stuff to const/let/arrow fn etc

thrown in some jsdoc also to help with typing

makes for better cross comp code in deno & browser without npm/bundler

### CODE REVIEW

**Comment by lydell** [comment]
Hi!

I really dislike this package. A while ago I inlined this code in another package I dislike – https://github.com/lydell/source-map-resolve/ – with the hope of the npm download count of this package falling so I could deprecate this without being too disruptive. That hasn’t really panned out, though, because most downloads of source-map-resolve comes from unmaintained packages that are locked on older versions of source-map-resolve.

Do you actually use this package? If so I’m curious – for what? Some thing Deno or browser based?

If you have use for something like this I’d recommend:

- Just coding exactly what you need in your app.
- Making your own package. If you do, please let me know so I can link to it as a possible replacement!

**Comment by jimmywarting** [comment]
> Do you actually use this package? If so I’m curious – for what? Some thing Deno or browser based?

I do not exactly use this package. it came from source-map-resolve as you said.
https://github.com/here-be/snapdragon/blob/fb340c536871669c83601ce6f6cb49d9ff730fac/package.json#L38

**Comment by lydell** [comment]
And you probably use snapdragon via [nanomatch](https://github.com/micromatch/nanomatch). IMO nanomatch should be deprecated too in favor of [micromatch](https://github.com/micromatch/micromatch)…

**Comment by jimmywarting** [comment]
That is correct

> And you probably use snapdragon via [nanomatch](https://github.com/micromatch/nanomatch). IMO nanomatch should be deprecated too in favor of [micromatch](https://github.com/micromatch/micromatch)…

that is correct

**Comment by lydell** [comment]
I have deprecated this package.

**Pull request closed without merging**
